name: merge-checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install deps
      run: |
        python -m pip install pre-commit
        rustup target add thumbv7em-none-eabihf
    - name: Lint
      run: pre-commit run --all-files --show-diff-on-failure
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --lib --target=x86_64-unknown-linux-gnu
    - name: Build examples
      run: cargo build --verbose --examples
